apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  annotations:
    github.com/project-slug: 3vanlock/backstage
    backstage.io/kubernetes-id: backstage
spec:
  type: service
  lifecycle: unknown
  owner: guests
